/**
 * Cross-language conformance test.
 *
 * Reads the JSON fixture emitted by the Python schema package and validates
 * every event against the TypeScript Zod schema. If this passes, we know the
 * two language implementations agree on the wire format byte-for-byte.
 *
 * The fixture is regenerated by:
 *
 *     .venv/Scripts/python.exe packages/schema-py/scripts/emit_fixtures.py
 *
 * Keeping this generated artifact under version control is intentional — it
 * doubles as a wire-format snapshot for code review.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  CognitiveEventBatchSchema,
  CognitiveEventSchema,
  RunCreateSchema,
  RunSchema,
  RunUpdateSchema,
  SCHEMA_VERSION,
} from "./index.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(here, "..", "test-fixtures", "python_emitted.json");

interface Fixture {
  schemaVersion: "1.0";
  generatedBy: string;
  events: unknown[];
  run: unknown;
  runCreate: unknown;
  runUpdate: unknown;
}

function loadFixture(): Fixture {
  const raw = readFileSync(fixturePath, "utf-8");
  return JSON.parse(raw) as Fixture;
}

describe("interop: Python-emitted fixtures parse against the TS Zod schema", () => {
  const fixture = loadFixture();

  it("fixture pins the same schema version", () => {
    expect(fixture.schemaVersion).toBe(SCHEMA_VERSION);
  });

  it("every event passes CognitiveEventSchema individually", () => {
    expect(fixture.events.length).toBeGreaterThan(0);
    for (const evt of fixture.events) {
      const r = CognitiveEventSchema.safeParse(evt);
      if (!r.success) {
        // Surface the offending event on failure so CI logs are diagnostic.
        // eslint-disable-next-line no-console
        console.error("event rejected:", JSON.stringify(evt));
        console.error(r.error.format());
      }
      expect(r.success).toBe(true);
    }
  });

  it("the full event array passes CognitiveEventBatchSchema", () => {
    const r = CognitiveEventBatchSchema.safeParse(fixture.events);
    expect(r.success).toBe(true);
  });

  it("Run, RunCreate, RunUpdate fixtures all validate", () => {
    expect(RunSchema.safeParse(fixture.run).success).toBe(true);
    expect(RunCreateSchema.safeParse(fixture.runCreate).success).toBe(true);
    expect(RunUpdateSchema.safeParse(fixture.runUpdate).success).toBe(true);
  });

  it("covers every payload _type at least once", () => {
    const seen = new Set<string>();
    for (const evt of fixture.events as Array<{ payload: { _type: string } }>) {
      seen.add(evt.payload._type);
    }
    // The 11 payload variants we expect to see in a representative fixture.
    const expected = [
      "goal",
      "tool",
      "memory",
      "retry",
      "reflection",
      "subagent",
      "validation",
      "context",
      "reasoning",
      "planner",
      "generic",
    ];
    for (const t of expected) {
      expect(seen.has(t)).toBe(true);
    }
  });
});
