"""Python-side conformance test for the cross-language fixture.

The same JSON fixture that the TypeScript Zod schema parses must round-trip
back through the Python Pydantic models. If the fixture drifts so that one
language can validate it but the other cannot, this test fails immediately.

The fixture is generated by ``scripts/emit_fixtures.py`` and committed to
``packages/schema/test-fixtures/python_emitted.json``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from reverie_schema import (
    SCHEMA_VERSION,
    CognitiveEvent,
    Run,
    RunCreate,
    RunUpdate,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_PATH = REPO_ROOT / "packages" / "schema" / "test-fixtures" / "python_emitted.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"fixture not found at {FIXTURE_PATH} — "
            "run scripts/emit_fixtures.py to generate it"
        )
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_fixture_pins_schema_version(fixture):
    assert fixture["schemaVersion"] == SCHEMA_VERSION


def test_every_event_round_trips(fixture):
    for raw in fixture["events"]:
        evt = CognitiveEvent.model_validate(raw)
        # And dumping it should produce JSON Pydantic itself can re-parse.
        re_dumped = json.loads(evt.model_dump_json())
        evt2 = CognitiveEvent.model_validate(re_dumped)
        assert evt == evt2


def test_run_models_validate(fixture):
    Run.model_validate(fixture["run"])
    RunCreate.model_validate(fixture["runCreate"])
    RunUpdate.model_validate(fixture["runUpdate"])


def test_fixture_covers_all_payload_kinds(fixture):
    seen = {evt["payload"]["_type"] for evt in fixture["events"]}
    expected = {
        "goal",
        "tool",
        "memory",
        "retry",
        "reflection",
        "subagent",
        "validation",
        "context",
        "reasoning",
        "planner",
        "generic",
    }
    missing = expected - seen
    assert not missing, f"fixture missing payload kinds: {missing}"
