"""Copy ``apps/web/out`` into ``apps/api/src/reverie_api/_web_static/``.

This step is run BEFORE building the ``reverie-api`` wheel so the static
web app travels inside the Python package. It's also useful during local
development if you want ``reverie start`` to skip pnpm.

Usage
-----

    pnpm -C apps/web build:static
    python scripts/bundle_web_app.py

Run with ``--clean`` to delete the bundled directory instead.

Idempotent — re-running overwrites the bundled copy. The bundled directory
is gitignored so this is safe to run on a clean checkout.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WEB_OUT = REPO_ROOT / "apps" / "web" / "out"
PACKAGE_TARGET = (
    REPO_ROOT / "apps" / "api" / "src" / "reverie_api" / "_web_static"
)


def bundle() -> int:
    if not WEB_OUT.exists() or not (WEB_OUT / "index.html").exists():
        print(
            f"error: static export not found at {WEB_OUT}\n"
            "       run 'pnpm -C apps/web build:static' first.",
            file=sys.stderr,
        )
        return 1

    if PACKAGE_TARGET.exists():
        shutil.rmtree(PACKAGE_TARGET)

    print(f"copying {WEB_OUT} -> {PACKAGE_TARGET}")
    shutil.copytree(WEB_OUT, PACKAGE_TARGET)

    # Touch a marker file so anyone inspecting the wheel can see what's here.
    (PACKAGE_TARGET / ".reverie-bundled").write_text(
        "Generated by scripts/bundle_web_app.py — do not edit by hand.\n",
        encoding="utf-8",
    )

    file_count = sum(1 for _ in PACKAGE_TARGET.rglob("*") if _.is_file())
    print(f"ok: bundled {file_count} files")
    return 0


def clean() -> int:
    if not PACKAGE_TARGET.exists():
        print(f"nothing to clean at {PACKAGE_TARGET}")
        return 0
    shutil.rmtree(PACKAGE_TARGET)
    print(f"removed {PACKAGE_TARGET}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the bundled web app directory instead of building it.",
    )
    args = parser.parse_args()
    return clean() if args.clean else bundle()


if __name__ == "__main__":
    sys.exit(main())
